#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollProcess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CTRCTSPayrollDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertJob(Job instance);
    partial void UpdateJob(Job instance);
    partial void DeleteJob(Job instance);
    partial void InsertClass(Class instance);
    partial void UpdateClass(Class instance);
    partial void DeleteClass(Class instance);
    partial void InsertEmpTypeTimeCode(EmpTypeTimeCode instance);
    partial void UpdateEmpTypeTimeCode(EmpTypeTimeCode instance);
    partial void DeleteEmpTypeTimeCode(EmpTypeTimeCode instance);
    partial void InsertPlant(Plant instance);
    partial void UpdatePlant(Plant instance);
    partial void DeletePlant(Plant instance);
    partial void InsertTimesheet(Timesheet instance);
    partial void UpdateTimesheet(Timesheet instance);
    partial void DeleteTimesheet(Timesheet instance);
    partial void InsertPayComponent(PayComponent instance);
    partial void UpdatePayComponent(PayComponent instance);
    partial void DeletePayComponent(PayComponent instance);
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    partial void InsertSetting(Setting instance);
    partial void UpdateSetting(Setting instance);
    partial void DeleteSetting(Setting instance);
    partial void InsertTimesheetData(TimesheetData instance);
    partial void UpdateTimesheetData(TimesheetData instance);
    partial void DeleteTimesheetData(TimesheetData instance);
    partial void InsertEmp_Allowance(Emp_Allowance instance);
    partial void UpdateEmp_Allowance(Emp_Allowance instance);
    partial void DeleteEmp_Allowance(Emp_Allowance instance);
    partial void InsertTSException(TSException instance);
    partial void UpdateTSException(TSException instance);
    partial void DeleteTSException(TSException instance);
    partial void InsertPayYear(PayYear instance);
    partial void UpdatePayYear(PayYear instance);
    partial void DeletePayYear(PayYear instance);
    partial void InsertEventLog(EventLog instance);
    partial void UpdateEventLog(EventLog instance);
    partial void DeleteEventLog(EventLog instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::PayrollProcess.Properties.Settings.Default.CTRCTSPayrollDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Job> Jobs
		{
			get
			{
				return this.GetTable<Job>();
			}
		}
		
		public System.Data.Linq.Table<Class> Classes
		{
			get
			{
				return this.GetTable<Class>();
			}
		}
		
		public System.Data.Linq.Table<EmpTypeTimeCode> EmpTypeTimeCodes
		{
			get
			{
				return this.GetTable<EmpTypeTimeCode>();
			}
		}
		
		public System.Data.Linq.Table<Plant> Plants
		{
			get
			{
				return this.GetTable<Plant>();
			}
		}
		
		public System.Data.Linq.Table<Timesheet> Timesheets
		{
			get
			{
				return this.GetTable<Timesheet>();
			}
		}
		
		public System.Data.Linq.Table<PayComponent> PayComponents
		{
			get
			{
				return this.GetTable<PayComponent>();
			}
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
		
		public System.Data.Linq.Table<Setting> Settings
		{
			get
			{
				return this.GetTable<Setting>();
			}
		}
		
		public System.Data.Linq.Table<TimesheetData> TimesheetDatas
		{
			get
			{
				return this.GetTable<TimesheetData>();
			}
		}
		
		public System.Data.Linq.Table<Emp_Allowance> Emp_Allowances
		{
			get
			{
				return this.GetTable<Emp_Allowance>();
			}
		}
		
		public System.Data.Linq.Table<TSException> TSExceptions
		{
			get
			{
				return this.GetTable<TSException>();
			}
		}
		
		public System.Data.Linq.Table<PayYear> PayYears
		{
			get
			{
				return this.GetTable<PayYear>();
			}
		}
		
		public System.Data.Linq.Table<EventLog> EventLogs
		{
			get
			{
				return this.GetTable<EventLog>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Jobs")]
	public partial class Job : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _JobCode;
		
		private string _JobDesc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJobCodeChanging(string value);
    partial void OnJobCodeChanged();
    partial void OnJobDescChanging(string value);
    partial void OnJobDescChanged();
    #endregion
		
		public Job()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string JobCode
		{
			get
			{
				return this._JobCode;
			}
			set
			{
				if ((this._JobCode != value))
				{
					this.OnJobCodeChanging(value);
					this.SendPropertyChanging();
					this._JobCode = value;
					this.SendPropertyChanged("JobCode");
					this.OnJobCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobDesc", DbType="NVarChar(50)")]
		public string JobDesc
		{
			get
			{
				return this._JobDesc;
			}
			set
			{
				if ((this._JobDesc != value))
				{
					this.OnJobDescChanging(value);
					this.SendPropertyChanging();
					this._JobDesc = value;
					this.SendPropertyChanged("JobDesc");
					this.OnJobDescChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Class")]
	public partial class Class : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PCSClassNo;
		
		private string _Emp_Condition;
		
		private string _GradeCodeID;
		
		private string _LevelCodeID;
		
		private System.Nullable<decimal> _HoursPerFN;
		
		private System.Nullable<decimal> _AmountPerFN;
		
		private System.Nullable<int> _PYCLASS_CLASSCODE;
		
		private string _PYCLASS_CLASSDESC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPCSClassNoChanging(int value);
    partial void OnPCSClassNoChanged();
    partial void OnEmp_ConditionChanging(string value);
    partial void OnEmp_ConditionChanged();
    partial void OnGradeCodeIDChanging(string value);
    partial void OnGradeCodeIDChanged();
    partial void OnLevelCodeIDChanging(string value);
    partial void OnLevelCodeIDChanged();
    partial void OnHoursPerFNChanging(System.Nullable<decimal> value);
    partial void OnHoursPerFNChanged();
    partial void OnAmountPerFNChanging(System.Nullable<decimal> value);
    partial void OnAmountPerFNChanged();
    partial void OnPYCLASS_CLASSCODEChanging(System.Nullable<int> value);
    partial void OnPYCLASS_CLASSCODEChanged();
    partial void OnPYCLASS_CLASSDESCChanging(string value);
    partial void OnPYCLASS_CLASSDESCChanged();
    #endregion
		
		public Class()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCSClassNo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PCSClassNo
		{
			get
			{
				return this._PCSClassNo;
			}
			set
			{
				if ((this._PCSClassNo != value))
				{
					this.OnPCSClassNoChanging(value);
					this.SendPropertyChanging();
					this._PCSClassNo = value;
					this.SendPropertyChanged("PCSClassNo");
					this.OnPCSClassNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Condition", DbType="NVarChar(50)")]
		public string Emp_Condition
		{
			get
			{
				return this._Emp_Condition;
			}
			set
			{
				if ((this._Emp_Condition != value))
				{
					this.OnEmp_ConditionChanging(value);
					this.SendPropertyChanging();
					this._Emp_Condition = value;
					this.SendPropertyChanged("Emp_Condition");
					this.OnEmp_ConditionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeCodeID", DbType="NVarChar(50)")]
		public string GradeCodeID
		{
			get
			{
				return this._GradeCodeID;
			}
			set
			{
				if ((this._GradeCodeID != value))
				{
					this.OnGradeCodeIDChanging(value);
					this.SendPropertyChanging();
					this._GradeCodeID = value;
					this.SendPropertyChanged("GradeCodeID");
					this.OnGradeCodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LevelCodeID", DbType="NVarChar(50)")]
		public string LevelCodeID
		{
			get
			{
				return this._LevelCodeID;
			}
			set
			{
				if ((this._LevelCodeID != value))
				{
					this.OnLevelCodeIDChanging(value);
					this.SendPropertyChanging();
					this._LevelCodeID = value;
					this.SendPropertyChanged("LevelCodeID");
					this.OnLevelCodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoursPerFN", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> HoursPerFN
		{
			get
			{
				return this._HoursPerFN;
			}
			set
			{
				if ((this._HoursPerFN != value))
				{
					this.OnHoursPerFNChanging(value);
					this.SendPropertyChanging();
					this._HoursPerFN = value;
					this.SendPropertyChanged("HoursPerFN");
					this.OnHoursPerFNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmountPerFN", DbType="Money")]
		public System.Nullable<decimal> AmountPerFN
		{
			get
			{
				return this._AmountPerFN;
			}
			set
			{
				if ((this._AmountPerFN != value))
				{
					this.OnAmountPerFNChanging(value);
					this.SendPropertyChanging();
					this._AmountPerFN = value;
					this.SendPropertyChanged("AmountPerFN");
					this.OnAmountPerFNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PYCLASS_CLASSCODE", DbType="Int")]
		public System.Nullable<int> PYCLASS_CLASSCODE
		{
			get
			{
				return this._PYCLASS_CLASSCODE;
			}
			set
			{
				if ((this._PYCLASS_CLASSCODE != value))
				{
					this.OnPYCLASS_CLASSCODEChanging(value);
					this.SendPropertyChanging();
					this._PYCLASS_CLASSCODE = value;
					this.SendPropertyChanged("PYCLASS_CLASSCODE");
					this.OnPYCLASS_CLASSCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PYCLASS_CLASSDESC", DbType="NVarChar(50)")]
		public string PYCLASS_CLASSDESC
		{
			get
			{
				return this._PYCLASS_CLASSDESC;
			}
			set
			{
				if ((this._PYCLASS_CLASSDESC != value))
				{
					this.OnPYCLASS_CLASSDESCChanging(value);
					this.SendPropertyChanging();
					this._PYCLASS_CLASSDESC = value;
					this.SendPropertyChanged("PYCLASS_CLASSDESC");
					this.OnPYCLASS_CLASSDESCChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmpTypeTimeCode")]
	public partial class EmpTypeTimeCode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TimeCode;
		
		private string _EmpType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTimeCodeChanging(int value);
    partial void OnTimeCodeChanged();
    partial void OnEmpTypeChanging(string value);
    partial void OnEmpTypeChanged();
    #endregion
		
		public EmpTypeTimeCode()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeCode", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TimeCode
		{
			get
			{
				return this._TimeCode;
			}
			set
			{
				if ((this._TimeCode != value))
				{
					this.OnTimeCodeChanging(value);
					this.SendPropertyChanging();
					this._TimeCode = value;
					this.SendPropertyChanged("TimeCode");
					this.OnTimeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpType", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string EmpType
		{
			get
			{
				return this._EmpType;
			}
			set
			{
				if ((this._EmpType != value))
				{
					this.OnEmpTypeChanging(value);
					this.SendPropertyChanging();
					this._EmpType = value;
					this.SendPropertyChanged("EmpType");
					this.OnEmpTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Plant")]
	public partial class Plant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PlantSource;
		
		private int _PlantTarget;
		
		private string _PlantDesc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPlantSourceChanging(string value);
    partial void OnPlantSourceChanged();
    partial void OnPlantTargetChanging(int value);
    partial void OnPlantTargetChanged();
    partial void OnPlantDescChanging(string value);
    partial void OnPlantDescChanged();
    #endregion
		
		public Plant()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlantSource", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PlantSource
		{
			get
			{
				return this._PlantSource;
			}
			set
			{
				if ((this._PlantSource != value))
				{
					this.OnPlantSourceChanging(value);
					this.SendPropertyChanging();
					this._PlantSource = value;
					this.SendPropertyChanged("PlantSource");
					this.OnPlantSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlantTarget", DbType="Int NOT NULL")]
		public int PlantTarget
		{
			get
			{
				return this._PlantTarget;
			}
			set
			{
				if ((this._PlantTarget != value))
				{
					this.OnPlantTargetChanging(value);
					this.SendPropertyChanging();
					this._PlantTarget = value;
					this.SendPropertyChanged("PlantTarget");
					this.OnPlantTargetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlantDesc", DbType="NVarChar(150)")]
		public string PlantDesc
		{
			get
			{
				return this._PlantDesc;
			}
			set
			{
				if ((this._PlantDesc != value))
				{
					this.OnPlantDescChanging(value);
					this.SendPropertyChanging();
					this._PlantDesc = value;
					this.SendPropertyChanged("PlantDesc");
					this.OnPlantDescChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Timesheets")]
	public partial class Timesheet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TimesheetID;
		
		private int _StaffID;
		
		private int _PayNoYear;
		
		private string _filename;
		
		private EntityRef<PayYear> _PayYear;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTimesheetIDChanging(int value);
    partial void OnTimesheetIDChanged();
    partial void OnStaffIDChanging(int value);
    partial void OnStaffIDChanged();
    partial void OnPayNoYearChanging(int value);
    partial void OnPayNoYearChanged();
    partial void OnfilenameChanging(string value);
    partial void OnfilenameChanged();
    #endregion
		
		public Timesheet()
		{
			this._PayYear = default(EntityRef<PayYear>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimesheetID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TimesheetID
		{
			get
			{
				return this._TimesheetID;
			}
			set
			{
				if ((this._TimesheetID != value))
				{
					this.OnTimesheetIDChanging(value);
					this.SendPropertyChanging();
					this._TimesheetID = value;
					this.SendPropertyChanged("TimesheetID");
					this.OnTimesheetIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffID", DbType="Int NOT NULL")]
		public int StaffID
		{
			get
			{
				return this._StaffID;
			}
			set
			{
				if ((this._StaffID != value))
				{
					this.OnStaffIDChanging(value);
					this.SendPropertyChanging();
					this._StaffID = value;
					this.SendPropertyChanged("StaffID");
					this.OnStaffIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayNoYear", DbType="Int NOT NULL")]
		public int PayNoYear
		{
			get
			{
				return this._PayNoYear;
			}
			set
			{
				if ((this._PayNoYear != value))
				{
					if (this._PayYear.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPayNoYearChanging(value);
					this.SendPropertyChanging();
					this._PayNoYear = value;
					this.SendPropertyChanged("PayNoYear");
					this.OnPayNoYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filename", DbType="NVarChar(500)")]
		public string filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				if ((this._filename != value))
				{
					this.OnfilenameChanging(value);
					this.SendPropertyChanging();
					this._filename = value;
					this.SendPropertyChanged("filename");
					this.OnfilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PayYear_Timesheet", Storage="_PayYear", ThisKey="PayNoYear", OtherKey="PayNoYear", IsForeignKey=true)]
		public PayYear PayYear
		{
			get
			{
				return this._PayYear.Entity;
			}
			set
			{
				PayYear previousValue = this._PayYear.Entity;
				if (((previousValue != value) 
							|| (this._PayYear.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PayYear.Entity = null;
						previousValue.Timesheets.Remove(this);
					}
					this._PayYear.Entity = value;
					if ((value != null))
					{
						value.Timesheets.Add(this);
						this._PayNoYear = value.PayNoYear;
					}
					else
					{
						this._PayNoYear = default(int);
					}
					this.SendPropertyChanged("PayYear");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PayComponent")]
	public partial class PayComponent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _PayCompCode;
		
		private string _PayCompDesc;
		
		private System.Nullable<int> _PayCompType;
		
		private string _PayCompTypeDesc;
		
		private string _Payment_deduct;
		
		private System.Nullable<int> _Units;
		
		private string _PayPeriodUnit;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPayCompCodeChanging(decimal value);
    partial void OnPayCompCodeChanged();
    partial void OnPayCompDescChanging(string value);
    partial void OnPayCompDescChanged();
    partial void OnPayCompTypeChanging(System.Nullable<int> value);
    partial void OnPayCompTypeChanged();
    partial void OnPayCompTypeDescChanging(string value);
    partial void OnPayCompTypeDescChanged();
    partial void OnPayment_deductChanging(string value);
    partial void OnPayment_deductChanged();
    partial void OnUnitsChanging(System.Nullable<int> value);
    partial void OnUnitsChanged();
    partial void OnPayPeriodUnitChanging(string value);
    partial void OnPayPeriodUnitChanged();
    #endregion
		
		public PayComponent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayCompCode", DbType="Decimal(18,1) NOT NULL", IsPrimaryKey=true)]
		public decimal PayCompCode
		{
			get
			{
				return this._PayCompCode;
			}
			set
			{
				if ((this._PayCompCode != value))
				{
					this.OnPayCompCodeChanging(value);
					this.SendPropertyChanging();
					this._PayCompCode = value;
					this.SendPropertyChanged("PayCompCode");
					this.OnPayCompCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayCompDesc", DbType="NVarChar(150)")]
		public string PayCompDesc
		{
			get
			{
				return this._PayCompDesc;
			}
			set
			{
				if ((this._PayCompDesc != value))
				{
					this.OnPayCompDescChanging(value);
					this.SendPropertyChanging();
					this._PayCompDesc = value;
					this.SendPropertyChanged("PayCompDesc");
					this.OnPayCompDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayCompType", DbType="Int")]
		public System.Nullable<int> PayCompType
		{
			get
			{
				return this._PayCompType;
			}
			set
			{
				if ((this._PayCompType != value))
				{
					this.OnPayCompTypeChanging(value);
					this.SendPropertyChanging();
					this._PayCompType = value;
					this.SendPropertyChanged("PayCompType");
					this.OnPayCompTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayCompTypeDesc", DbType="NVarChar(150)")]
		public string PayCompTypeDesc
		{
			get
			{
				return this._PayCompTypeDesc;
			}
			set
			{
				if ((this._PayCompTypeDesc != value))
				{
					this.OnPayCompTypeDescChanging(value);
					this.SendPropertyChanging();
					this._PayCompTypeDesc = value;
					this.SendPropertyChanged("PayCompTypeDesc");
					this.OnPayCompTypeDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment_deduct", DbType="NVarChar(150)")]
		public string Payment_deduct
		{
			get
			{
				return this._Payment_deduct;
			}
			set
			{
				if ((this._Payment_deduct != value))
				{
					this.OnPayment_deductChanging(value);
					this.SendPropertyChanging();
					this._Payment_deduct = value;
					this.SendPropertyChanged("Payment_deduct");
					this.OnPayment_deductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Units", DbType="Int")]
		public System.Nullable<int> Units
		{
			get
			{
				return this._Units;
			}
			set
			{
				if ((this._Units != value))
				{
					this.OnUnitsChanging(value);
					this.SendPropertyChanging();
					this._Units = value;
					this.SendPropertyChanged("Units");
					this.OnUnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayPeriodUnit", DbType="NVarChar(50)")]
		public string PayPeriodUnit
		{
			get
			{
				return this._PayPeriodUnit;
			}
			set
			{
				if ((this._PayPeriodUnit != value))
				{
					this.OnPayPeriodUnitChanging(value);
					this.SendPropertyChanging();
					this._PayPeriodUnit = value;
					this.SendPropertyChanged("PayPeriodUnit");
					this.OnPayPeriodUnitChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employees")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _T1EmpNo;
		
		private string _Surname;
		
		private string _FirstName;
		
		private System.Nullable<char> _Emp_Type;
		
		private System.Nullable<decimal> _Hours;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnT1EmpNoChanging(int value);
    partial void OnT1EmpNoChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnEmp_TypeChanging(System.Nullable<char> value);
    partial void OnEmp_TypeChanged();
    partial void OnHoursChanging(System.Nullable<decimal> value);
    partial void OnHoursChanged();
    #endregion
		
		public Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T1EmpNo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int T1EmpNo
		{
			get
			{
				return this._T1EmpNo;
			}
			set
			{
				if ((this._T1EmpNo != value))
				{
					this.OnT1EmpNoChanging(value);
					this.SendPropertyChanging();
					this._T1EmpNo = value;
					this.SendPropertyChanged("T1EmpNo");
					this.OnT1EmpNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(50)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Type", DbType="Char(1)")]
		public System.Nullable<char> Emp_Type
		{
			get
			{
				return this._Emp_Type;
			}
			set
			{
				if ((this._Emp_Type != value))
				{
					this.OnEmp_TypeChanging(value);
					this.SendPropertyChanging();
					this._Emp_Type = value;
					this.SendPropertyChanged("Emp_Type");
					this.OnEmp_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hours", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Hours
		{
			get
			{
				return this._Hours;
			}
			set
			{
				if ((this._Hours != value))
				{
					this.OnHoursChanging(value);
					this.SendPropertyChanging();
					this._Hours = value;
					this.SendPropertyChanged("Hours");
					this.OnHoursChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Settings")]
	public partial class Setting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SettingCode;
		
		private string _SettingDesc;
		
		private string _Vals;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSettingCodeChanging(string value);
    partial void OnSettingCodeChanged();
    partial void OnSettingDescChanging(string value);
    partial void OnSettingDescChanged();
    partial void OnValsChanging(string value);
    partial void OnValsChanged();
    #endregion
		
		public Setting()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettingCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SettingCode
		{
			get
			{
				return this._SettingCode;
			}
			set
			{
				if ((this._SettingCode != value))
				{
					this.OnSettingCodeChanging(value);
					this.SendPropertyChanging();
					this._SettingCode = value;
					this.SendPropertyChanged("SettingCode");
					this.OnSettingCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettingDesc", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string SettingDesc
		{
			get
			{
				return this._SettingDesc;
			}
			set
			{
				if ((this._SettingDesc != value))
				{
					this.OnSettingDescChanging(value);
					this.SendPropertyChanging();
					this._SettingDesc = value;
					this.SendPropertyChanged("SettingDesc");
					this.OnSettingDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vals", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Vals
		{
			get
			{
				return this._Vals;
			}
			set
			{
				if ((this._Vals != value))
				{
					this.OnValsChanging(value);
					this.SendPropertyChanging();
					this._Vals = value;
					this.SendPropertyChanged("Vals");
					this.OnValsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TimesheetData")]
	public partial class TimesheetData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _job;
		
		private System.DateTime _start_date;
		
		private System.DateTime _end_date;
		
		private int _TimesheetID;
		
		private string _Description;
		
		private System.Nullable<int> _ClassNo;
		
		private decimal _AllowanceCode;
		
		private System.Nullable<decimal> _TImeCode;
		
		private System.Nullable<int> _PlantNo;
		
		private System.Nullable<int> _Row;
		
		private string _Source;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnjobChanging(string value);
    partial void OnjobChanged();
    partial void Onstart_dateChanging(System.DateTime value);
    partial void Onstart_dateChanged();
    partial void Onend_dateChanging(System.DateTime value);
    partial void Onend_dateChanged();
    partial void OnTimesheetIDChanging(int value);
    partial void OnTimesheetIDChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnClassNoChanging(System.Nullable<int> value);
    partial void OnClassNoChanged();
    partial void OnAllowanceCodeChanging(decimal value);
    partial void OnAllowanceCodeChanged();
    partial void OnTImeCodeChanging(System.Nullable<decimal> value);
    partial void OnTImeCodeChanged();
    partial void OnPlantNoChanging(System.Nullable<int> value);
    partial void OnPlantNoChanged();
    partial void OnRowChanging(System.Nullable<int> value);
    partial void OnRowChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    #endregion
		
		public TimesheetData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string job
		{
			get
			{
				return this._job;
			}
			set
			{
				if ((this._job != value))
				{
					this.OnjobChanging(value);
					this.SendPropertyChanging();
					this._job = value;
					this.SendPropertyChanged("job");
					this.OnjobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_date", DbType="DateTime NOT NULL")]
		public System.DateTime start_date
		{
			get
			{
				return this._start_date;
			}
			set
			{
				if ((this._start_date != value))
				{
					this.Onstart_dateChanging(value);
					this.SendPropertyChanging();
					this._start_date = value;
					this.SendPropertyChanged("start_date");
					this.Onstart_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_date", DbType="DateTime NOT NULL")]
		public System.DateTime end_date
		{
			get
			{
				return this._end_date;
			}
			set
			{
				if ((this._end_date != value))
				{
					this.Onend_dateChanging(value);
					this.SendPropertyChanging();
					this._end_date = value;
					this.SendPropertyChanged("end_date");
					this.Onend_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimesheetID", DbType="Int NOT NULL")]
		public int TimesheetID
		{
			get
			{
				return this._TimesheetID;
			}
			set
			{
				if ((this._TimesheetID != value))
				{
					this.OnTimesheetIDChanging(value);
					this.SendPropertyChanging();
					this._TimesheetID = value;
					this.SendPropertyChanged("TimesheetID");
					this.OnTimesheetIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(150)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassNo", DbType="Int")]
		public System.Nullable<int> ClassNo
		{
			get
			{
				return this._ClassNo;
			}
			set
			{
				if ((this._ClassNo != value))
				{
					this.OnClassNoChanging(value);
					this.SendPropertyChanging();
					this._ClassNo = value;
					this.SendPropertyChanged("ClassNo");
					this.OnClassNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowanceCode", DbType="Decimal(18,1) NOT NULL")]
		public decimal AllowanceCode
		{
			get
			{
				return this._AllowanceCode;
			}
			set
			{
				if ((this._AllowanceCode != value))
				{
					this.OnAllowanceCodeChanging(value);
					this.SendPropertyChanging();
					this._AllowanceCode = value;
					this.SendPropertyChanged("AllowanceCode");
					this.OnAllowanceCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TImeCode", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> TImeCode
		{
			get
			{
				return this._TImeCode;
			}
			set
			{
				if ((this._TImeCode != value))
				{
					this.OnTImeCodeChanging(value);
					this.SendPropertyChanging();
					this._TImeCode = value;
					this.SendPropertyChanged("TImeCode");
					this.OnTImeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlantNo", DbType="Int")]
		public System.Nullable<int> PlantNo
		{
			get
			{
				return this._PlantNo;
			}
			set
			{
				if ((this._PlantNo != value))
				{
					this.OnPlantNoChanging(value);
					this.SendPropertyChanging();
					this._PlantNo = value;
					this.SendPropertyChanged("PlantNo");
					this.OnPlantNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Row", DbType="Int")]
		public System.Nullable<int> Row
		{
			get
			{
				return this._Row;
			}
			set
			{
				if ((this._Row != value))
				{
					this.OnRowChanging(value);
					this.SendPropertyChanging();
					this._Row = value;
					this.SendPropertyChanged("Row");
					this.OnRowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(255)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Emp_Allowances")]
	public partial class Emp_Allowance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _T1_EmpID;
		
		private decimal _PayComponentCode;
		
		private System.Nullable<decimal> _units;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnT1_EmpIDChanging(int value);
    partial void OnT1_EmpIDChanged();
    partial void OnPayComponentCodeChanging(decimal value);
    partial void OnPayComponentCodeChanged();
    partial void OnunitsChanging(System.Nullable<decimal> value);
    partial void OnunitsChanged();
    #endregion
		
		public Emp_Allowance()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T1_EmpID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int T1_EmpID
		{
			get
			{
				return this._T1_EmpID;
			}
			set
			{
				if ((this._T1_EmpID != value))
				{
					this.OnT1_EmpIDChanging(value);
					this.SendPropertyChanging();
					this._T1_EmpID = value;
					this.SendPropertyChanged("T1_EmpID");
					this.OnT1_EmpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayComponentCode", DbType="Decimal(10,1) NOT NULL", IsPrimaryKey=true)]
		public decimal PayComponentCode
		{
			get
			{
				return this._PayComponentCode;
			}
			set
			{
				if ((this._PayComponentCode != value))
				{
					this.OnPayComponentCodeChanging(value);
					this.SendPropertyChanging();
					this._PayComponentCode = value;
					this.SendPropertyChanged("PayComponentCode");
					this.OnPayComponentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_units", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> units
		{
			get
			{
				return this._units;
			}
			set
			{
				if ((this._units != value))
				{
					this.OnunitsChanging(value);
					this.SendPropertyChanging();
					this._units = value;
					this.SendPropertyChanged("units");
					this.OnunitsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TSException")]
	public partial class TSException : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TimesheetID;
		
		private string _Field;
		
		private string _Exception;
		
		private string _Filename;
		
		private System.Nullable<bool> _Error_elseWarning;
		
		private string _EmpIdent;
		
		private string _Tab;
		
		private System.Nullable<int> _EmpNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTimesheetIDChanging(int value);
    partial void OnTimesheetIDChanged();
    partial void OnFieldChanging(string value);
    partial void OnFieldChanged();
    partial void OnExceptionChanging(string value);
    partial void OnExceptionChanged();
    partial void OnFilenameChanging(string value);
    partial void OnFilenameChanged();
    partial void OnError_elseWarningChanging(System.Nullable<bool> value);
    partial void OnError_elseWarningChanged();
    partial void OnEmpIdentChanging(string value);
    partial void OnEmpIdentChanged();
    partial void OnTabChanging(string value);
    partial void OnTabChanged();
    partial void OnEmpNoChanging(System.Nullable<int> value);
    partial void OnEmpNoChanged();
    #endregion
		
		public TSException()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimesheetID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TimesheetID
		{
			get
			{
				return this._TimesheetID;
			}
			set
			{
				if ((this._TimesheetID != value))
				{
					this.OnTimesheetIDChanging(value);
					this.SendPropertyChanging();
					this._TimesheetID = value;
					this.SendPropertyChanged("TimesheetID");
					this.OnTimesheetIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Field
		{
			get
			{
				return this._Field;
			}
			set
			{
				if ((this._Field != value))
				{
					this.OnFieldChanging(value);
					this.SendPropertyChanging();
					this._Field = value;
					this.SendPropertyChanged("Field");
					this.OnFieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exception", DbType="NVarChar(500)")]
		public string Exception
		{
			get
			{
				return this._Exception;
			}
			set
			{
				if ((this._Exception != value))
				{
					this.OnExceptionChanging(value);
					this.SendPropertyChanging();
					this._Exception = value;
					this.SendPropertyChanged("Exception");
					this.OnExceptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filename", DbType="NVarChar(200)")]
		public string Filename
		{
			get
			{
				return this._Filename;
			}
			set
			{
				if ((this._Filename != value))
				{
					this.OnFilenameChanging(value);
					this.SendPropertyChanging();
					this._Filename = value;
					this.SendPropertyChanged("Filename");
					this.OnFilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error_elseWarning", DbType="Bit")]
		public System.Nullable<bool> Error_elseWarning
		{
			get
			{
				return this._Error_elseWarning;
			}
			set
			{
				if ((this._Error_elseWarning != value))
				{
					this.OnError_elseWarningChanging(value);
					this.SendPropertyChanging();
					this._Error_elseWarning = value;
					this.SendPropertyChanged("Error_elseWarning");
					this.OnError_elseWarningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpIdent", DbType="NVarChar(200)")]
		public string EmpIdent
		{
			get
			{
				return this._EmpIdent;
			}
			set
			{
				if ((this._EmpIdent != value))
				{
					this.OnEmpIdentChanging(value);
					this.SendPropertyChanging();
					this._EmpIdent = value;
					this.SendPropertyChanged("EmpIdent");
					this.OnEmpIdentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tab", DbType="NVarChar(150)")]
		public string Tab
		{
			get
			{
				return this._Tab;
			}
			set
			{
				if ((this._Tab != value))
				{
					this.OnTabChanging(value);
					this.SendPropertyChanging();
					this._Tab = value;
					this.SendPropertyChanged("Tab");
					this.OnTabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpNo", DbType="Int")]
		public System.Nullable<int> EmpNo
		{
			get
			{
				return this._EmpNo;
			}
			set
			{
				if ((this._EmpNo != value))
				{
					this.OnEmpNoChanging(value);
					this.SendPropertyChanging();
					this._EmpNo = value;
					this.SendPropertyChanged("EmpNo");
					this.OnEmpNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PayYear")]
	public partial class PayYear : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _StartDate;
		
		private System.DateTime _EndDate;
		
		private int _PayNoYear;
		
		private string _Comment;
		
		private EntitySet<Timesheet> _Timesheets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStartDateChanging(System.DateTime value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.DateTime value);
    partial void OnEndDateChanged();
    partial void OnPayNoYearChanging(int value);
    partial void OnPayNoYearChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    #endregion
		
		public PayYear()
		{
			this._Timesheets = new EntitySet<Timesheet>(new Action<Timesheet>(this.attach_Timesheets), new Action<Timesheet>(this.detach_Timesheets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime NOT NULL")]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime NOT NULL")]
		public System.DateTime EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayNoYear", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PayNoYear
		{
			get
			{
				return this._PayNoYear;
			}
			set
			{
				if ((this._PayNoYear != value))
				{
					this.OnPayNoYearChanging(value);
					this.SendPropertyChanging();
					this._PayNoYear = value;
					this.SendPropertyChanged("PayNoYear");
					this.OnPayNoYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(250)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PayYear_Timesheet", Storage="_Timesheets", ThisKey="PayNoYear", OtherKey="PayNoYear")]
		public EntitySet<Timesheet> Timesheets
		{
			get
			{
				return this._Timesheets;
			}
			set
			{
				this._Timesheets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Timesheets(Timesheet entity)
		{
			this.SendPropertyChanging();
			entity.PayYear = this;
		}
		
		private void detach_Timesheets(Timesheet entity)
		{
			this.SendPropertyChanging();
			entity.PayYear = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EventLog")]
	public partial class EventLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EventLogID;
		
		private System.Nullable<System.DateTime> _EventDT;
		
		private string _Filename;
		
		private string _Error;
		
		private System.Nullable<System.Guid> _EventGroup;
		
		private string _TabSheet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEventLogIDChanging(int value);
    partial void OnEventLogIDChanged();
    partial void OnEventDTChanging(System.Nullable<System.DateTime> value);
    partial void OnEventDTChanged();
    partial void OnFilenameChanging(string value);
    partial void OnFilenameChanged();
    partial void OnErrorChanging(string value);
    partial void OnErrorChanged();
    partial void OnEventGroupChanging(System.Nullable<System.Guid> value);
    partial void OnEventGroupChanged();
    partial void OnTabSheetChanging(string value);
    partial void OnTabSheetChanged();
    #endregion
		
		public EventLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventLogID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EventLogID
		{
			get
			{
				return this._EventLogID;
			}
			set
			{
				if ((this._EventLogID != value))
				{
					this.OnEventLogIDChanging(value);
					this.SendPropertyChanging();
					this._EventLogID = value;
					this.SendPropertyChanged("EventLogID");
					this.OnEventLogIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> EventDT
		{
			get
			{
				return this._EventDT;
			}
			set
			{
				if ((this._EventDT != value))
				{
					this.OnEventDTChanging(value);
					this.SendPropertyChanging();
					this._EventDT = value;
					this.SendPropertyChanged("EventDT");
					this.OnEventDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filename", DbType="NVarChar(150)")]
		public string Filename
		{
			get
			{
				return this._Filename;
			}
			set
			{
				if ((this._Filename != value))
				{
					this.OnFilenameChanging(value);
					this.SendPropertyChanging();
					this._Filename = value;
					this.SendPropertyChanged("Filename");
					this.OnFilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="NVarChar(500)")]
		public string Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this.OnErrorChanging(value);
					this.SendPropertyChanging();
					this._Error = value;
					this.SendPropertyChanged("Error");
					this.OnErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventGroup", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> EventGroup
		{
			get
			{
				return this._EventGroup;
			}
			set
			{
				if ((this._EventGroup != value))
				{
					this.OnEventGroupChanging(value);
					this.SendPropertyChanging();
					this._EventGroup = value;
					this.SendPropertyChanged("EventGroup");
					this.OnEventGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TabSheet", DbType="NVarChar(50)")]
		public string TabSheet
		{
			get
			{
				return this._TabSheet;
			}
			set
			{
				if ((this._TabSheet != value))
				{
					this.OnTabSheetChanging(value);
					this.SendPropertyChanging();
					this._TabSheet = value;
					this.SendPropertyChanged("TabSheet");
					this.OnTabSheetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
