//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollProcess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql2014;Initial Catalog=CTRCTSPayrollDB;Integrated Security=False;Con" +
            "nect Timeout=30;UID=PayrollApp;PWD=RQkTuemu;")]
        public string CTRCTSPayrollDBConnectionString1oldold {
            get {
                return ((string)(this["CTRCTSPayrollDBConnectionString1oldold"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=svrsql001;Initial Catalog=CTRCTSPayroll;Integrated Security=False;Con" +
            "nect Timeout=30;UID=payrollDB;PWD=Payroll2023;")]
        public string CTRCTSPayrollDBConnectionString1new {
            get {
                return ((string)(this["CTRCTSPayrollDBConnectionString1new"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=CTRCTSPayrollDB;Integrated Security=true;")]
        public string CTRCTSPayrollDBConnectionString1 {
            get {
                return ((string)(this["CTRCTSPayrollDBConnectionString1"]));
            }
        }
    }
}
